[workspace]
members = ["krpc-build"]

[package]
name = "krpc-client"
version = "0.4.1-0.5.1"
edition = "2021"
authors = ["Kyle Ladd <kyle@ladd.io>"]
description = "A stand-alone client for the Kerbal Space Program kRPC mod."
documentation = "https://docs.rs/krpc-client"
repository = "https://github.com/kladd/krpc-client"
license = "GPL-3.0"

[features]
docs = ["krpc-build/docs"]

[dependencies]
thiserror = "1.0"
protobuf = { version = "3.2.0", features = ["bytes"] }
bytes = "1.4"

[build-dependencies]
krpc-build = { path = "./krpc-build" }
protobuf-codegen = "3.2.0"