[package]
name = "krpc-client"
version = "1.0.0"
edition = "2021"

[dependencies]
bytes = "1.1"
prost = "0.9"
protobuf = "2.25.2"
num-derive = "0.3"
num-traits = "0.2"

[build-dependencies]
prost-build = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
convert_case = "0.5"