[package]
name = "krpc-client"
version = "0.2.0-0.4.9-1.12.1+nullprofile"
edition = "2021"

[dependencies]
thiserror = "1.0"
protobuf = { version = "3.1.0", features = ["bytes"] }
bytes = "1.1"

[build-dependencies]
krpc-build = { path = "./krpc-build" }
protobuf-codegen = "3.1.0"