[package]
name = "krpc-client"
version = "0.3.0-0.5.1-1.12.5"
edition = "2021"

[dependencies]
thiserror = "1.0"
protobuf = { version = "3.2.0", features = ["bytes"] }
bytes = "1.4"

[build-dependencies]
krpc-build = { path = "./krpc-build" }
protobuf-codegen = "3.2.0"