[package]
name = "krpc-client"
version = "0.4.9"
edition = "2021"

[dependencies]
bytes = "1.1"
prost = "0.9"
protobuf = "2.25.2"

[build-dependencies]
prost-build = "0.9"
krpc-build = { path = "./krpc-build" }