[package]
name = "krpc-client"
version = "0.4.9"
edition = "2021"

[dependencies]
protobuf = { version = "3.0.0-alpha.8", features = ["bytes"] }
bytes = "1.1"

[build-dependencies]
krpc-build = { path = "./krpc-build" }
protobuf-codegen = "3.0.0-alpha.8"