edition = "2021"
max_width = 80
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

wrap_comments = true
comment_width = 60
normalize_comments = true
doc_comment_code_block_width = 80
format_code_in_doc_comments = true
